### ISSUE TITLE
addind resource

### ISSUE THREAD

**Issue by montoyamoraga** [Open-Source-Studio-at-ITP/Resources#1]
i liked these interviews by Kyle McDonald, maybe they help for this class
https://github.com/kylemcdonald/SharingInterviews

**Comment by shiffman** [comment]
Added with https://github.com/Open-Source-Studio-at-ITP/Resources/commit/e9ec4f267eee5a5f13ae7e29efe173fb7a532af4, thanks for the suggestion!
