### ISSUE TITLE
GitHub Resources

### ISSUE THREAD

**Issue by petrspelos** [Open-Source-Studio-at-ITP/Resources#2]
_This is probably super obvious and redundant and I'm sorry in advance..._ :blush: 

However, when learning about Open Source and contributing to it, I really found myself coming back to GitHub's resources, :tada: especially the [Open Source Guides](https://opensource.guide/). It is a collection of amazing and well written resources. :slightly_smiling_face: 

And of course, on the very bottom of Github's [Explore page](https://github.com/explore) are literally "Resources for Open Source". :+1: 
![screen](https://i.imgur.com/uGkpxSj.png)

**Comment by shiffman** [comment]
I've done an initial pass over `README.md`, it includes the open source guides but there are many links in the Explore area referenced by @petrspelos that could be added! Pull requests welcome!

**Comment by shiffman** [comment]
Closing, please feel free to re-open if there are still elements to be added!
